"""MkDocs hook: regenerate docs/reference/cli.md from the abt-tools Typer app.

Runs `python -m typer abt-tools.py utils docs` (from inside abtv2-tools/, so
Typer's own doc generator can import the script by file path) before every
build, so the CLI reference can never drift from the code. abtv2-tools/abt
isn't an installed package (no build metadata in its pyproject.toml -- see
docs/project/contributing.md), so this targets abt-tools.py by path rather
than a module name; Typer's `python -m typer` CLI supports both. Needs
abtv2-tools/requirements-dev.txt (or its env.yaml conda env) installed
alongside requirements-docs.txt in whichever environment runs `mkdocs
build`, so `abt.cli_funcs` and everything it imports (pydantic, psycopg2,
boto3, ...) is importable by `sys.executable`.

The file is only rewritten when its content changes, which keeps `mkdocs
serve` from rebuild-looping.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
ABTV2_TOOLS_DIR = REPO_ROOT / "abtv2-tools"
CLI_NAME = "abt-tools"

HEADER = """\
<!-- THIS FILE IS GENERATED by docs/_hooks/gen_cli_reference.py at docs build
     time from abt-tools.py's own Typer app. Edit the CLI help text in
     abtv2-tools/abt/cli_funcs/*.py, not this file -- `mkdocs build`
     regenerates it, and a committed copy is kept so the page is browsable
     on GitHub without running a build. -->

# `abt-tools` CLI Reference

`abt-tools.py` is the single CLI for the ABT pipeline -- every stage
(download, import, carto, export, bundler, vundler) plus one debug command
dispatches through it. This page is generated from the CLI's own help text
at docs build time, so it is always in sync with the code.

!!! tip "Run it from abtv2-tools/"
    Every example in this documentation invokes it as
    `python abt-tools.py <command> [options]` from inside the `abtv2-tools/`
    checkout, alongside its sibling `rbt-schema/` (see
    [Repository Tour](../overview/repo-tour.md)).

"""


def on_pre_build(config) -> None:  # noqa: ANN001 - mkdocs hook signature
    result = subprocess.run(
        [sys.executable, "-m", "typer", "abt-tools.py", "utils", "docs", "--name", CLI_NAME],
        cwd=ABTV2_TOOLS_DIR,
        capture_output=True,
        text=True,
        check=True,
    )
    # Drop the generator's own H1 (we provide our own header above).
    body = result.stdout
    marker = f"# `{CLI_NAME}`"
    if body.startswith(marker):
        body = body.split("\n", 1)[1].lstrip("\n")
    content = HEADER + body
    target = Path(config["docs_dir"]) / "reference" / "cli.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    if not target.exists() or target.read_text(encoding="utf-8") != content:
        target.write_text(content, encoding="utf-8")
