"""MkDocs hook: regenerate docs/schema/layers.md from rbt-schema/export/*.json.

Every export/*.json (and disabled export/*.json.skip -- see "The .skip
convention" on docs/schema/adding-a-layer.md) file describes one output
vector tile layer. This hook builds one table row per file so the registry
can never drift from the actual layer configs. Disabled layers are listed
too, flagged as disabled, rather than silently omitted.

The file is only rewritten when its content changes, which keeps `mkdocs
serve` from rebuild-looping.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
EXPORT_DIR = REPO_ROOT / "rbt-schema" / "export"

HEADER = """\
<!-- THIS FILE IS GENERATED by docs/_hooks/gen_layer_registry.py at docs
     build time from rbt-schema/export/*.json (and *.json.skip). Edit those
     files, not this one -- `mkdocs build` regenerates it, and a committed
     copy is kept so the page is browsable on GitHub without running a
     build. -->

# Layer Registry

Every row below is one [`rbt-schema/export/*.json`](../schema/adding-a-layer.md)
file -- one output vector tile layer. See [Adding a Layer](adding-a-layer.md)
for the field reference and how to add a new one.

"""


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _layer_id_for(path: Path, config: dict, *, skipped: bool) -> str:
    if "layer_id" in config:
        return config["layer_id"]
    # A ".json.skip" file's own .stem still ends in ".json" (e.g.
    # "building_polygon.json.skip" -> stem "building_polygon.json") --
    # strip that too before falling back to it as a layer_id guess.
    return Path(path.stem).stem if skipped else path.stem


def _row(layer_id: str, config: dict, *, skipped: bool) -> str:
    tippecanoe = config.get("tippecanoe_options") or {}
    attributes = config.get("attributes") or []
    min_zoom = tippecanoe.get("minimum_zoom", "")
    max_zoom = tippecanoe.get("maximum_zoom", "")
    geometry_type = config.get("geometry_type", "")
    flags = tippecanoe.get("additional_flags") or ""
    flags_cell = f"`{flags}`" if flags else ""
    status = "**disabled** (`.skip`)" if skipped else "enabled"
    return (
        f"| `{layer_id}` | {geometry_type} | {min_zoom} | {max_zoom} "
        f"| {len(attributes)} | {flags_cell} | {status} |"
    )


def _generate_table() -> str:
    rows: list[tuple[str, str]] = []
    for path in sorted(EXPORT_DIR.glob("*.json")):
        config = _load(path)
        layer_id = _layer_id_for(path, config, skipped=False)
        rows.append((layer_id, _row(layer_id, config, skipped=False)))
    for path in sorted(EXPORT_DIR.glob("*.json.skip")):
        config = _load(path)
        layer_id = _layer_id_for(path, config, skipped=True)
        rows.append((layer_id, _row(layer_id, config, skipped=True)))
    rows.sort(key=lambda pair: pair[0])

    lines = [
        f"{len(rows)} layers total "
        f"({sum(1 for _, r in rows if 'disabled' not in r)} enabled, "
        f"{sum(1 for _, r in rows if 'disabled' in r)} disabled).",
        "",
        "| Layer ID | Geometry | Min Zoom | Max Zoom | Attributes | Tippecanoe flags | Status |",
        "|---|---|---|---|---|---|---|",
    ]
    lines.extend(row for _, row in rows)
    return "\n".join(lines) + "\n"


def on_pre_build(config) -> None:  # noqa: ANN001 - mkdocs hook signature
    content = HEADER + _generate_table()
    target = Path(config["docs_dir"]) / "schema" / "layers.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    if not target.exists() or target.read_text(encoding="utf-8") != content:
        target.write_text(content, encoding="utf-8")
