"""MkDocs hook: regenerate docs/overview/data-sources.md from
rbt-schema/import/aux_data/*.json and rbt-schema/tile-metadata/metadata.py.

Combines the "what dataset, from where" side (aux_data/*.json -- see
docs/schema/aux-data.md for the config format) with the "what license"
side (tile-metadata/metadata.py's `license` list -- the same dict `bundler`
writes into the final mbtiles, see docs/schema/tile-metadata.md) into one
attribution/licensing reference, so neither table can drift from the other
or from what's actually configured.

The file is only rewritten when its content changes, which keeps `mkdocs
serve` from rebuild-looping.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
AUX_DATA_DIR = REPO_ROOT / "rbt-schema" / "import" / "aux_data"
METADATA_PATH = REPO_ROOT / "rbt-schema" / "tile-metadata" / "metadata.py"

HEADER = """\
<!-- THIS FILE IS GENERATED by docs/_hooks/gen_data_sources.py at docs build
     time from rbt-schema/import/aux_data/*.json and
     rbt-schema/tile-metadata/metadata.py. Edit those files, not this one --
     `mkdocs build` regenerates it, and a committed copy is kept so the page
     is browsable on GitHub without running a build. -->

# Data Sources & Licensing

RBT combines OpenStreetMap with a number of auxiliary open datasets, each
configured as one [`rbt-schema/import/aux_data/*.json`](../schema/aux-data.md)
file. The table below is generated from those files. License terms below are
from [`rbt-schema/tile-metadata/metadata.py`](../schema/tile-metadata.md),
the same dict `bundler` writes into the final `.mbtiles`.

"""


def _load_metadata() -> dict:
    spec = importlib.util.spec_from_file_location("tile_metadata", METADATA_PATH)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load metadata module from {METADATA_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.metadata


def _aux_sources_section() -> str:
    lines = [
        "## Auxiliary sources",
        "",
        "| Source | Origin | Format | Layers loaded |",
        "|---|---|---|---|",
    ]
    for path in sorted(AUX_DATA_DIR.glob("*.json")):
        config = json.loads(path.read_text(encoding="utf-8"))
        folder_name = config.get("folder_name", path.stem)
        url = config.get("url")
        local_path = config.get("local_path")
        origin = f"[{url}]({url})" if url else f"`{local_path}` (bundled in-repo)"
        file_type = config.get("type", "")
        aux_load = config.get("aux_load", []) or []
        layer_names = [
            entry.get("aux_layer_name") or entry.get("aux_folder_name") or "?"
            for entry in aux_load
        ]
        layers_cell = ", ".join(f"`aux_data.{name}`" for name in layer_names)
        lines.append(f"| `{folder_name}` | {origin} | {file_type} | {layers_cell} |")
    lines.append("")
    lines.append(
        "OSM data itself (the other input alongside these auxiliary sources) "
        "is loaded via [imposm mappings](../schema/osm-mappings.md), not an "
        "`aux_data/*.json` config, and isn't listed above."
    )
    return "\n".join(lines) + "\n"


def _license_section(metadata: dict) -> str:
    tileset_name = metadata.get("name", "this tileset")
    lines = [
        "## Licenses",
        "",
        f"Per `tile-metadata/metadata.py`, **{tileset_name}** combines the "
        "following licensed sources:",
        "",
        "| Source | License |",
        "|---|---|",
    ]
    for entry in metadata.get("license", []) or []:
        name = entry.get("name", "")
        license_name = entry.get("license", "")
        url = entry.get("url", "")
        source_cell = f"[{name}]({url})" if url else name
        lines.append(f"| {source_cell} | {license_name} |")

    attribution = metadata.get("attribution", "")
    if attribution:
        lines.extend([
            "",
            "Attribution string embedded in the bundled `.mbtiles`:",
            "",
            f"> {attribution}",
        ])

    tags = metadata.get("tags") or []
    if tags:
        lines.extend(["", "Tags: " + ", ".join(f"`{tag}`" for tag in tags)])

    return "\n".join(lines) + "\n"


def on_pre_build(config) -> None:  # noqa: ANN001 - mkdocs hook signature
    metadata = _load_metadata()
    content = HEADER + _aux_sources_section() + "\n" + _license_section(metadata)
    target = Path(config["docs_dir"]) / "overview" / "data-sources.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    if not target.exists() or target.read_text(encoding="utf-8") != content:
        target.write_text(content, encoding="utf-8")
